// Generated by gencpp from file wam_control/BHandGraspVel.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_BHANDGRASPVEL_H
#define WAM_CONTROL_MESSAGE_BHANDGRASPVEL_H

#include <ros/service_traits.h>


#include <wam_control/BHandGraspVelRequest.h>
#include <wam_control/BHandGraspVelResponse.h>


namespace wam_control
{

struct BHandGraspVel
{

typedef BHandGraspVelRequest Request;
typedef BHandGraspVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandGraspVel
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::BHandGraspVel > {
  static const char* value()
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const ::wam_control::BHandGraspVel&) { return value(); }
};

template<>
struct DataType< ::wam_control::BHandGraspVel > {
  static const char* value()
  {
    return "wam_control/BHandGraspVel";
  }

  static const char* value(const ::wam_control::BHandGraspVel&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::BHandGraspVelRequest> should match 
// service_traits::MD5Sum< ::wam_control::BHandGraspVel > 
template<>
struct MD5Sum< ::wam_control::BHandGraspVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_control::BHandGraspVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::BHandGraspVelRequest> should match 
// service_traits::DataType< ::wam_control::BHandGraspVel > 
template<>
struct DataType< ::wam_control::BHandGraspVelRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_control::BHandGraspVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::BHandGraspVelResponse> should match 
// service_traits::MD5Sum< ::wam_control::BHandGraspVel > 
template<>
struct MD5Sum< ::wam_control::BHandGraspVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_control::BHandGraspVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::BHandGraspVelResponse> should match 
// service_traits::DataType< ::wam_control::BHandGraspVel > 
template<>
struct DataType< ::wam_control::BHandGraspVelResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::BHandGraspVel >::value();
  }
  static const char* value(const ::wam_control::BHandGraspVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_BHANDGRASPVEL_H
