// Generated by gencpp from file wam_control/BHandSpreadVel.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_BHANDSPREADVEL_H
#define WAM_CONTROL_MESSAGE_BHANDSPREADVEL_H

#include <ros/service_traits.h>


#include <wam_control/BHandSpreadVelRequest.h>
#include <wam_control/BHandSpreadVelResponse.h>


namespace wam_control
{

struct BHandSpreadVel
{

typedef BHandSpreadVelRequest Request;
typedef BHandSpreadVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandSpreadVel
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::BHandSpreadVel > {
  static const char* value()
  {
    return "e4ff88b32504f688719a85e0753f63ce";
  }

  static const char* value(const ::wam_control::BHandSpreadVel&) { return value(); }
};

template<>
struct DataType< ::wam_control::BHandSpreadVel > {
  static const char* value()
  {
    return "wam_control/BHandSpreadVel";
  }

  static const char* value(const ::wam_control::BHandSpreadVel&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::BHandSpreadVelRequest> should match 
// service_traits::MD5Sum< ::wam_control::BHandSpreadVel > 
template<>
struct MD5Sum< ::wam_control::BHandSpreadVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_control::BHandSpreadVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::BHandSpreadVelRequest> should match 
// service_traits::DataType< ::wam_control::BHandSpreadVel > 
template<>
struct DataType< ::wam_control::BHandSpreadVelRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_control::BHandSpreadVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::BHandSpreadVelResponse> should match 
// service_traits::MD5Sum< ::wam_control::BHandSpreadVel > 
template<>
struct MD5Sum< ::wam_control::BHandSpreadVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_control::BHandSpreadVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::BHandSpreadVelResponse> should match 
// service_traits::DataType< ::wam_control::BHandSpreadVel > 
template<>
struct DataType< ::wam_control::BHandSpreadVelResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::BHandSpreadVel >::value();
  }
  static const char* value(const ::wam_control::BHandSpreadVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_BHANDSPREADVEL_H
