// Generated by gencpp from file wam_control/BHandFingerVel.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_BHANDFINGERVEL_H
#define WAM_CONTROL_MESSAGE_BHANDFINGERVEL_H

#include <ros/service_traits.h>


#include <wam_control/BHandFingerVelRequest.h>
#include <wam_control/BHandFingerVelResponse.h>


namespace wam_control
{

struct BHandFingerVel
{

typedef BHandFingerVelRequest Request;
typedef BHandFingerVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandFingerVel
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::BHandFingerVel > {
  static const char* value()
  {
    return "d4b1534f81253843d8e7435f97fbf189";
  }

  static const char* value(const ::wam_control::BHandFingerVel&) { return value(); }
};

template<>
struct DataType< ::wam_control::BHandFingerVel > {
  static const char* value()
  {
    return "wam_control/BHandFingerVel";
  }

  static const char* value(const ::wam_control::BHandFingerVel&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::BHandFingerVelRequest> should match 
// service_traits::MD5Sum< ::wam_control::BHandFingerVel > 
template<>
struct MD5Sum< ::wam_control::BHandFingerVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_control::BHandFingerVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::BHandFingerVelRequest> should match 
// service_traits::DataType< ::wam_control::BHandFingerVel > 
template<>
struct DataType< ::wam_control::BHandFingerVelRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_control::BHandFingerVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::BHandFingerVelResponse> should match 
// service_traits::MD5Sum< ::wam_control::BHandFingerVel > 
template<>
struct MD5Sum< ::wam_control::BHandFingerVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_control::BHandFingerVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::BHandFingerVelResponse> should match 
// service_traits::DataType< ::wam_control::BHandFingerVel > 
template<>
struct DataType< ::wam_control::BHandFingerVelResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::BHandFingerVel >::value();
  }
  static const char* value(const ::wam_control::BHandFingerVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_BHANDFINGERVEL_H
