// Generated by gencpp from file wam_control/BHandSpreadPos.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_BHANDSPREADPOS_H
#define WAM_CONTROL_MESSAGE_BHANDSPREADPOS_H

#include <ros/service_traits.h>


#include <wam_control/BHandSpreadPosRequest.h>
#include <wam_control/BHandSpreadPosResponse.h>


namespace wam_control
{

struct BHandSpreadPos
{

typedef BHandSpreadPosRequest Request;
typedef BHandSpreadPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandSpreadPos
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::BHandSpreadPos > {
  static const char* value()
  {
    return "718158cfca4f89c6952f799c53697f42";
  }

  static const char* value(const ::wam_control::BHandSpreadPos&) { return value(); }
};

template<>
struct DataType< ::wam_control::BHandSpreadPos > {
  static const char* value()
  {
    return "wam_control/BHandSpreadPos";
  }

  static const char* value(const ::wam_control::BHandSpreadPos&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::BHandSpreadPosRequest> should match 
// service_traits::MD5Sum< ::wam_control::BHandSpreadPos > 
template<>
struct MD5Sum< ::wam_control::BHandSpreadPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_control::BHandSpreadPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::BHandSpreadPosRequest> should match 
// service_traits::DataType< ::wam_control::BHandSpreadPos > 
template<>
struct DataType< ::wam_control::BHandSpreadPosRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_control::BHandSpreadPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::BHandSpreadPosResponse> should match 
// service_traits::MD5Sum< ::wam_control::BHandSpreadPos > 
template<>
struct MD5Sum< ::wam_control::BHandSpreadPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_control::BHandSpreadPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::BHandSpreadPosResponse> should match 
// service_traits::DataType< ::wam_control::BHandSpreadPos > 
template<>
struct DataType< ::wam_control::BHandSpreadPosResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::BHandSpreadPos >::value();
  }
  static const char* value(const ::wam_control::BHandSpreadPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_BHANDSPREADPOS_H
