// Generated by gencpp from file wam_control/BHandFingerPos.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_BHANDFINGERPOS_H
#define WAM_CONTROL_MESSAGE_BHANDFINGERPOS_H

#include <ros/service_traits.h>


#include <wam_control/BHandFingerPosRequest.h>
#include <wam_control/BHandFingerPosResponse.h>


namespace wam_control
{

struct BHandFingerPos
{

typedef BHandFingerPosRequest Request;
typedef BHandFingerPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BHandFingerPos
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::BHandFingerPos > {
  static const char* value()
  {
    return "b8c122f38450d0302ba1a30c9c588995";
  }

  static const char* value(const ::wam_control::BHandFingerPos&) { return value(); }
};

template<>
struct DataType< ::wam_control::BHandFingerPos > {
  static const char* value()
  {
    return "wam_control/BHandFingerPos";
  }

  static const char* value(const ::wam_control::BHandFingerPos&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::BHandFingerPosRequest> should match 
// service_traits::MD5Sum< ::wam_control::BHandFingerPos > 
template<>
struct MD5Sum< ::wam_control::BHandFingerPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_control::BHandFingerPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::BHandFingerPosRequest> should match 
// service_traits::DataType< ::wam_control::BHandFingerPos > 
template<>
struct DataType< ::wam_control::BHandFingerPosRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_control::BHandFingerPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::BHandFingerPosResponse> should match 
// service_traits::MD5Sum< ::wam_control::BHandFingerPos > 
template<>
struct MD5Sum< ::wam_control::BHandFingerPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_control::BHandFingerPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::BHandFingerPosResponse> should match 
// service_traits::DataType< ::wam_control::BHandFingerPos > 
template<>
struct DataType< ::wam_control::BHandFingerPosResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::BHandFingerPos >::value();
  }
  static const char* value(const ::wam_control::BHandFingerPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_BHANDFINGERPOS_H
