// Generated by gencpp from file wam_control/CartVel.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_CARTVEL_H
#define WAM_CONTROL_MESSAGE_CARTVEL_H

#include <ros/service_traits.h>


#include <wam_control/CartVelRequest.h>
#include <wam_control/CartVelResponse.h>


namespace wam_control
{

struct CartVel
{

typedef CartVelRequest Request;
typedef CartVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CartVel
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::CartVel > {
  static const char* value()
  {
    return "acd45b1363369bbb5ad0077b51700f8e";
  }

  static const char* value(const ::wam_control::CartVel&) { return value(); }
};

template<>
struct DataType< ::wam_control::CartVel > {
  static const char* value()
  {
    return "wam_control/CartVel";
  }

  static const char* value(const ::wam_control::CartVel&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::CartVelRequest> should match 
// service_traits::MD5Sum< ::wam_control::CartVel > 
template<>
struct MD5Sum< ::wam_control::CartVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::CartVel >::value();
  }
  static const char* value(const ::wam_control::CartVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::CartVelRequest> should match 
// service_traits::DataType< ::wam_control::CartVel > 
template<>
struct DataType< ::wam_control::CartVelRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::CartVel >::value();
  }
  static const char* value(const ::wam_control::CartVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::CartVelResponse> should match 
// service_traits::MD5Sum< ::wam_control::CartVel > 
template<>
struct MD5Sum< ::wam_control::CartVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::CartVel >::value();
  }
  static const char* value(const ::wam_control::CartVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::CartVelResponse> should match 
// service_traits::DataType< ::wam_control::CartVel > 
template<>
struct DataType< ::wam_control::CartVelResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::CartVel >::value();
  }
  static const char* value(const ::wam_control::CartVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_CARTVEL_H
