// Generated by gencpp from file wam_control/CartPosMove.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_CARTPOSMOVE_H
#define WAM_CONTROL_MESSAGE_CARTPOSMOVE_H

#include <ros/service_traits.h>


#include <wam_control/CartPosMoveRequest.h>
#include <wam_control/CartPosMoveResponse.h>


namespace wam_control
{

struct CartPosMove
{

typedef CartPosMoveRequest Request;
typedef CartPosMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CartPosMove
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::CartPosMove > {
  static const char* value()
  {
    return "993d3a0cca92114d34b338aeb1007ee4";
  }

  static const char* value(const ::wam_control::CartPosMove&) { return value(); }
};

template<>
struct DataType< ::wam_control::CartPosMove > {
  static const char* value()
  {
    return "wam_control/CartPosMove";
  }

  static const char* value(const ::wam_control::CartPosMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::CartPosMoveRequest> should match 
// service_traits::MD5Sum< ::wam_control::CartPosMove > 
template<>
struct MD5Sum< ::wam_control::CartPosMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::CartPosMove >::value();
  }
  static const char* value(const ::wam_control::CartPosMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::CartPosMoveRequest> should match 
// service_traits::DataType< ::wam_control::CartPosMove > 
template<>
struct DataType< ::wam_control::CartPosMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::CartPosMove >::value();
  }
  static const char* value(const ::wam_control::CartPosMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::CartPosMoveResponse> should match 
// service_traits::MD5Sum< ::wam_control::CartPosMove > 
template<>
struct MD5Sum< ::wam_control::CartPosMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::CartPosMove >::value();
  }
  static const char* value(const ::wam_control::CartPosMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::CartPosMoveResponse> should match 
// service_traits::DataType< ::wam_control::CartPosMove > 
template<>
struct DataType< ::wam_control::CartPosMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::CartPosMove >::value();
  }
  static const char* value(const ::wam_control::CartPosMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_CARTPOSMOVE_H
