// Generated by gencpp from file wam_control/FollowPath.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_FOLLOWPATH_H
#define WAM_CONTROL_MESSAGE_FOLLOWPATH_H

#include <ros/service_traits.h>


#include <wam_control/FollowPathRequest.h>
#include <wam_control/FollowPathResponse.h>


namespace wam_control
{

struct FollowPath
{

typedef FollowPathRequest Request;
typedef FollowPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FollowPath
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::FollowPath > {
  static const char* value()
  {
    return "d84f5b474d984f3bb9b08180eaffe23c";
  }

  static const char* value(const ::wam_control::FollowPath&) { return value(); }
};

template<>
struct DataType< ::wam_control::FollowPath > {
  static const char* value()
  {
    return "wam_control/FollowPath";
  }

  static const char* value(const ::wam_control::FollowPath&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::FollowPathRequest> should match 
// service_traits::MD5Sum< ::wam_control::FollowPath > 
template<>
struct MD5Sum< ::wam_control::FollowPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::FollowPath >::value();
  }
  static const char* value(const ::wam_control::FollowPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::FollowPathRequest> should match 
// service_traits::DataType< ::wam_control::FollowPath > 
template<>
struct DataType< ::wam_control::FollowPathRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::FollowPath >::value();
  }
  static const char* value(const ::wam_control::FollowPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::FollowPathResponse> should match 
// service_traits::MD5Sum< ::wam_control::FollowPath > 
template<>
struct MD5Sum< ::wam_control::FollowPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::FollowPath >::value();
  }
  static const char* value(const ::wam_control::FollowPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::FollowPathResponse> should match 
// service_traits::DataType< ::wam_control::FollowPath > 
template<>
struct DataType< ::wam_control::FollowPathResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::FollowPath >::value();
  }
  static const char* value(const ::wam_control::FollowPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_FOLLOWPATH_H
