// Generated by gencpp from file wam_control/ForceTorqueTool.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_FORCETORQUETOOL_H
#define WAM_CONTROL_MESSAGE_FORCETORQUETOOL_H

#include <ros/service_traits.h>


#include <wam_control/ForceTorqueToolRequest.h>
#include <wam_control/ForceTorqueToolResponse.h>


namespace wam_control
{

struct ForceTorqueTool
{

typedef ForceTorqueToolRequest Request;
typedef ForceTorqueToolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ForceTorqueTool
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::ForceTorqueTool > {
  static const char* value()
  {
    return "58646800d530c83853f5e010d6ccce9c";
  }

  static const char* value(const ::wam_control::ForceTorqueTool&) { return value(); }
};

template<>
struct DataType< ::wam_control::ForceTorqueTool > {
  static const char* value()
  {
    return "wam_control/ForceTorqueTool";
  }

  static const char* value(const ::wam_control::ForceTorqueTool&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::ForceTorqueToolRequest> should match 
// service_traits::MD5Sum< ::wam_control::ForceTorqueTool > 
template<>
struct MD5Sum< ::wam_control::ForceTorqueToolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::ForceTorqueTool >::value();
  }
  static const char* value(const ::wam_control::ForceTorqueToolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::ForceTorqueToolRequest> should match 
// service_traits::DataType< ::wam_control::ForceTorqueTool > 
template<>
struct DataType< ::wam_control::ForceTorqueToolRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::ForceTorqueTool >::value();
  }
  static const char* value(const ::wam_control::ForceTorqueToolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::ForceTorqueToolResponse> should match 
// service_traits::MD5Sum< ::wam_control::ForceTorqueTool > 
template<>
struct MD5Sum< ::wam_control::ForceTorqueToolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::ForceTorqueTool >::value();
  }
  static const char* value(const ::wam_control::ForceTorqueToolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::ForceTorqueToolResponse> should match 
// service_traits::DataType< ::wam_control::ForceTorqueTool > 
template<>
struct DataType< ::wam_control::ForceTorqueToolResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::ForceTorqueTool >::value();
  }
  static const char* value(const ::wam_control::ForceTorqueToolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_FORCETORQUETOOL_H
