// Generated by gencpp from file wam_control/GetToolPoseResponse.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_GETTOOLPOSERESPONSE_H
#define WAM_CONTROL_MESSAGE_GETTOOLPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_control
{
template <class ContainerAllocator>
struct GetToolPoseResponse_
{
  typedef GetToolPoseResponse_<ContainerAllocator> Type;

  GetToolPoseResponse_()
    : cart_position()
    , quaternion()  {
    }
  GetToolPoseResponse_(const ContainerAllocator& _alloc)
    : cart_position(_alloc)
    , quaternion(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _cart_position_type;
  _cart_position_type cart_position;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _quaternion_type;
  _quaternion_type quaternion;




  typedef boost::shared_ptr< ::wam_control::GetToolPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_control::GetToolPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetToolPoseResponse_

typedef ::wam_control::GetToolPoseResponse_<std::allocator<void> > GetToolPoseResponse;

typedef boost::shared_ptr< ::wam_control::GetToolPoseResponse > GetToolPoseResponsePtr;
typedef boost::shared_ptr< ::wam_control::GetToolPoseResponse const> GetToolPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_control::GetToolPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_control::GetToolPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wam_control': ['/home/fuego/reach_and_grasp_ws/src/wam_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_control::GetToolPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_control::GetToolPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_control::GetToolPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_control::GetToolPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_control::GetToolPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_control::GetToolPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_control::GetToolPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22b5d52b152019a59472ce937086458c";
  }

  static const char* value(const ::wam_control::GetToolPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22b5d52b152019a5ULL;
  static const uint64_t static_value2 = 0x9472ce937086458cULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_control::GetToolPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_control/GetToolPoseResponse";
  }

  static const char* value(const ::wam_control::GetToolPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_control::GetToolPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] cart_position\n\
float32[] quaternion\n\
";
  }

  static const char* value(const ::wam_control::GetToolPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_control::GetToolPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cart_position);
      stream.next(m.quaternion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetToolPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_control::GetToolPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_control::GetToolPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "cart_position[]" << std::endl;
    for (size_t i = 0; i < v.cart_position.size(); ++i)
    {
      s << indent << "  cart_position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.cart_position[i]);
    }
    s << indent << "quaternion[]" << std::endl;
    for (size_t i = 0; i < v.quaternion.size(); ++i)
    {
      s << indent << "  quaternion[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.quaternion[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_GETTOOLPOSERESPONSE_H
