// Generated by gencpp from file wam_control/GetToolPose.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_GETTOOLPOSE_H
#define WAM_CONTROL_MESSAGE_GETTOOLPOSE_H

#include <ros/service_traits.h>


#include <wam_control/GetToolPoseRequest.h>
#include <wam_control/GetToolPoseResponse.h>


namespace wam_control
{

struct GetToolPose
{

typedef GetToolPoseRequest Request;
typedef GetToolPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetToolPose
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::GetToolPose > {
  static const char* value()
  {
    return "b976353334f69a24896bcd9fdcff5c9d";
  }

  static const char* value(const ::wam_control::GetToolPose&) { return value(); }
};

template<>
struct DataType< ::wam_control::GetToolPose > {
  static const char* value()
  {
    return "wam_control/GetToolPose";
  }

  static const char* value(const ::wam_control::GetToolPose&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::GetToolPoseRequest> should match 
// service_traits::MD5Sum< ::wam_control::GetToolPose > 
template<>
struct MD5Sum< ::wam_control::GetToolPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::GetToolPose >::value();
  }
  static const char* value(const ::wam_control::GetToolPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::GetToolPoseRequest> should match 
// service_traits::DataType< ::wam_control::GetToolPose > 
template<>
struct DataType< ::wam_control::GetToolPoseRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::GetToolPose >::value();
  }
  static const char* value(const ::wam_control::GetToolPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::GetToolPoseResponse> should match 
// service_traits::MD5Sum< ::wam_control::GetToolPose > 
template<>
struct MD5Sum< ::wam_control::GetToolPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::GetToolPose >::value();
  }
  static const char* value(const ::wam_control::GetToolPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::GetToolPoseResponse> should match 
// service_traits::DataType< ::wam_control::GetToolPose > 
template<>
struct DataType< ::wam_control::GetToolPoseResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::GetToolPose >::value();
  }
  static const char* value(const ::wam_control::GetToolPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_GETTOOLPOSE_H
