// Generated by gencpp from file wam_control/GravityComp.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_GRAVITYCOMP_H
#define WAM_CONTROL_MESSAGE_GRAVITYCOMP_H

#include <ros/service_traits.h>


#include <wam_control/GravityCompRequest.h>
#include <wam_control/GravityCompResponse.h>


namespace wam_control
{

struct GravityComp
{

typedef GravityCompRequest Request;
typedef GravityCompResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GravityComp
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::GravityComp > {
  static const char* value()
  {
    return "f83a9fe078fab9865d863fbf215e1c14";
  }

  static const char* value(const ::wam_control::GravityComp&) { return value(); }
};

template<>
struct DataType< ::wam_control::GravityComp > {
  static const char* value()
  {
    return "wam_control/GravityComp";
  }

  static const char* value(const ::wam_control::GravityComp&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::GravityCompRequest> should match 
// service_traits::MD5Sum< ::wam_control::GravityComp > 
template<>
struct MD5Sum< ::wam_control::GravityCompRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::GravityComp >::value();
  }
  static const char* value(const ::wam_control::GravityCompRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::GravityCompRequest> should match 
// service_traits::DataType< ::wam_control::GravityComp > 
template<>
struct DataType< ::wam_control::GravityCompRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::GravityComp >::value();
  }
  static const char* value(const ::wam_control::GravityCompRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::GravityCompResponse> should match 
// service_traits::MD5Sum< ::wam_control::GravityComp > 
template<>
struct MD5Sum< ::wam_control::GravityCompResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::GravityComp >::value();
  }
  static const char* value(const ::wam_control::GravityCompResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::GravityCompResponse> should match 
// service_traits::DataType< ::wam_control::GravityComp > 
template<>
struct DataType< ::wam_control::GravityCompResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::GravityComp >::value();
  }
  static const char* value(const ::wam_control::GravityCompResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_GRAVITYCOMP_H
