// Generated by gencpp from file wam_control/Hold.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_HOLD_H
#define WAM_CONTROL_MESSAGE_HOLD_H

#include <ros/service_traits.h>


#include <wam_control/HoldRequest.h>
#include <wam_control/HoldResponse.h>


namespace wam_control
{

struct Hold
{

typedef HoldRequest Request;
typedef HoldResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Hold
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::Hold > {
  static const char* value()
  {
    return "797a139a4299aebd587b00a7001c67f7";
  }

  static const char* value(const ::wam_control::Hold&) { return value(); }
};

template<>
struct DataType< ::wam_control::Hold > {
  static const char* value()
  {
    return "wam_control/Hold";
  }

  static const char* value(const ::wam_control::Hold&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::HoldRequest> should match 
// service_traits::MD5Sum< ::wam_control::Hold > 
template<>
struct MD5Sum< ::wam_control::HoldRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::Hold >::value();
  }
  static const char* value(const ::wam_control::HoldRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::HoldRequest> should match 
// service_traits::DataType< ::wam_control::Hold > 
template<>
struct DataType< ::wam_control::HoldRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::Hold >::value();
  }
  static const char* value(const ::wam_control::HoldRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::HoldResponse> should match 
// service_traits::MD5Sum< ::wam_control::Hold > 
template<>
struct MD5Sum< ::wam_control::HoldResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::Hold >::value();
  }
  static const char* value(const ::wam_control::HoldResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::HoldResponse> should match 
// service_traits::DataType< ::wam_control::Hold > 
template<>
struct DataType< ::wam_control::HoldResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::Hold >::value();
  }
  static const char* value(const ::wam_control::HoldResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_HOLD_H
