// Generated by gencpp from file wam_control/JointMoveBlock.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_JOINTMOVEBLOCK_H
#define WAM_CONTROL_MESSAGE_JOINTMOVEBLOCK_H

#include <ros/service_traits.h>


#include <wam_control/JointMoveBlockRequest.h>
#include <wam_control/JointMoveBlockResponse.h>


namespace wam_control
{

struct JointMoveBlock
{

typedef JointMoveBlockRequest Request;
typedef JointMoveBlockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointMoveBlock
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::JointMoveBlock > {
  static const char* value()
  {
    return "a35c2d19fdef1f1b6b9cace11da2b5c6";
  }

  static const char* value(const ::wam_control::JointMoveBlock&) { return value(); }
};

template<>
struct DataType< ::wam_control::JointMoveBlock > {
  static const char* value()
  {
    return "wam_control/JointMoveBlock";
  }

  static const char* value(const ::wam_control::JointMoveBlock&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::JointMoveBlockRequest> should match 
// service_traits::MD5Sum< ::wam_control::JointMoveBlock > 
template<>
struct MD5Sum< ::wam_control::JointMoveBlockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::JointMoveBlock >::value();
  }
  static const char* value(const ::wam_control::JointMoveBlockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::JointMoveBlockRequest> should match 
// service_traits::DataType< ::wam_control::JointMoveBlock > 
template<>
struct DataType< ::wam_control::JointMoveBlockRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::JointMoveBlock >::value();
  }
  static const char* value(const ::wam_control::JointMoveBlockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::JointMoveBlockResponse> should match 
// service_traits::MD5Sum< ::wam_control::JointMoveBlock > 
template<>
struct MD5Sum< ::wam_control::JointMoveBlockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::JointMoveBlock >::value();
  }
  static const char* value(const ::wam_control::JointMoveBlockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::JointMoveBlockResponse> should match 
// service_traits::DataType< ::wam_control::JointMoveBlock > 
template<>
struct DataType< ::wam_control::JointMoveBlockResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::JointMoveBlock >::value();
  }
  static const char* value(const ::wam_control::JointMoveBlockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_JOINTMOVEBLOCK_H
