// Generated by gencpp from file wam_control/Link.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_LINK_H
#define WAM_CONTROL_MESSAGE_LINK_H

#include <ros/service_traits.h>


#include <wam_control/LinkRequest.h>
#include <wam_control/LinkResponse.h>


namespace wam_control
{

struct Link
{

typedef LinkRequest Request;
typedef LinkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Link
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::Link > {
  static const char* value()
  {
    return "a40ccb098e8ae81c40c4d8ba9679b483";
  }

  static const char* value(const ::wam_control::Link&) { return value(); }
};

template<>
struct DataType< ::wam_control::Link > {
  static const char* value()
  {
    return "wam_control/Link";
  }

  static const char* value(const ::wam_control::Link&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::LinkRequest> should match 
// service_traits::MD5Sum< ::wam_control::Link > 
template<>
struct MD5Sum< ::wam_control::LinkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::Link >::value();
  }
  static const char* value(const ::wam_control::LinkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::LinkRequest> should match 
// service_traits::DataType< ::wam_control::Link > 
template<>
struct DataType< ::wam_control::LinkRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::Link >::value();
  }
  static const char* value(const ::wam_control::LinkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::LinkResponse> should match 
// service_traits::MD5Sum< ::wam_control::Link > 
template<>
struct MD5Sum< ::wam_control::LinkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::Link >::value();
  }
  static const char* value(const ::wam_control::LinkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::LinkResponse> should match 
// service_traits::DataType< ::wam_control::Link > 
template<>
struct DataType< ::wam_control::LinkResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::Link >::value();
  }
  static const char* value(const ::wam_control::LinkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_LINK_H
