// Generated by gencpp from file wam_control/OrtnSplitMove.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_ORTNSPLITMOVE_H
#define WAM_CONTROL_MESSAGE_ORTNSPLITMOVE_H

#include <ros/service_traits.h>


#include <wam_control/OrtnSplitMoveRequest.h>
#include <wam_control/OrtnSplitMoveResponse.h>


namespace wam_control
{

struct OrtnSplitMove
{

typedef OrtnSplitMoveRequest Request;
typedef OrtnSplitMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OrtnSplitMove
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::OrtnSplitMove > {
  static const char* value()
  {
    return "d493f6e469f2b52d5ef0e3d041ef18b7";
  }

  static const char* value(const ::wam_control::OrtnSplitMove&) { return value(); }
};

template<>
struct DataType< ::wam_control::OrtnSplitMove > {
  static const char* value()
  {
    return "wam_control/OrtnSplitMove";
  }

  static const char* value(const ::wam_control::OrtnSplitMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::OrtnSplitMoveRequest> should match 
// service_traits::MD5Sum< ::wam_control::OrtnSplitMove > 
template<>
struct MD5Sum< ::wam_control::OrtnSplitMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::OrtnSplitMove >::value();
  }
  static const char* value(const ::wam_control::OrtnSplitMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::OrtnSplitMoveRequest> should match 
// service_traits::DataType< ::wam_control::OrtnSplitMove > 
template<>
struct DataType< ::wam_control::OrtnSplitMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::OrtnSplitMove >::value();
  }
  static const char* value(const ::wam_control::OrtnSplitMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::OrtnSplitMoveResponse> should match 
// service_traits::MD5Sum< ::wam_control::OrtnSplitMove > 
template<>
struct MD5Sum< ::wam_control::OrtnSplitMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::OrtnSplitMove >::value();
  }
  static const char* value(const ::wam_control::OrtnSplitMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::OrtnSplitMoveResponse> should match 
// service_traits::DataType< ::wam_control::OrtnSplitMove > 
template<>
struct DataType< ::wam_control::OrtnSplitMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::OrtnSplitMove >::value();
  }
  static const char* value(const ::wam_control::OrtnSplitMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_ORTNSPLITMOVE_H
