// Generated by gencpp from file wam_control/OrtnMove.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_ORTNMOVE_H
#define WAM_CONTROL_MESSAGE_ORTNMOVE_H

#include <ros/service_traits.h>


#include <wam_control/OrtnMoveRequest.h>
#include <wam_control/OrtnMoveResponse.h>


namespace wam_control
{

struct OrtnMove
{

typedef OrtnMoveRequest Request;
typedef OrtnMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OrtnMove
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::OrtnMove > {
  static const char* value()
  {
    return "86f723fe9a4be8979be87cd065276584";
  }

  static const char* value(const ::wam_control::OrtnMove&) { return value(); }
};

template<>
struct DataType< ::wam_control::OrtnMove > {
  static const char* value()
  {
    return "wam_control/OrtnMove";
  }

  static const char* value(const ::wam_control::OrtnMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::OrtnMoveRequest> should match 
// service_traits::MD5Sum< ::wam_control::OrtnMove > 
template<>
struct MD5Sum< ::wam_control::OrtnMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::OrtnMove >::value();
  }
  static const char* value(const ::wam_control::OrtnMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::OrtnMoveRequest> should match 
// service_traits::DataType< ::wam_control::OrtnMove > 
template<>
struct DataType< ::wam_control::OrtnMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::OrtnMove >::value();
  }
  static const char* value(const ::wam_control::OrtnMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::OrtnMoveResponse> should match 
// service_traits::MD5Sum< ::wam_control::OrtnMove > 
template<>
struct MD5Sum< ::wam_control::OrtnMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::OrtnMove >::value();
  }
  static const char* value(const ::wam_control::OrtnMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::OrtnMoveResponse> should match 
// service_traits::DataType< ::wam_control::OrtnMove > 
template<>
struct DataType< ::wam_control::OrtnMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::OrtnMove >::value();
  }
  static const char* value(const ::wam_control::OrtnMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_ORTNMOVE_H
