// Generated by gencpp from file wam_control/Play.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_PLAY_H
#define WAM_CONTROL_MESSAGE_PLAY_H

#include <ros/service_traits.h>


#include <wam_control/PlayRequest.h>
#include <wam_control/PlayResponse.h>


namespace wam_control
{

struct Play
{

typedef PlayRequest Request;
typedef PlayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Play
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::Play > {
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::wam_control::Play&) { return value(); }
};

template<>
struct DataType< ::wam_control::Play > {
  static const char* value()
  {
    return "wam_control/Play";
  }

  static const char* value(const ::wam_control::Play&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::PlayRequest> should match 
// service_traits::MD5Sum< ::wam_control::Play > 
template<>
struct MD5Sum< ::wam_control::PlayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::Play >::value();
  }
  static const char* value(const ::wam_control::PlayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::PlayRequest> should match 
// service_traits::DataType< ::wam_control::Play > 
template<>
struct DataType< ::wam_control::PlayRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::Play >::value();
  }
  static const char* value(const ::wam_control::PlayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::PlayResponse> should match 
// service_traits::MD5Sum< ::wam_control::Play > 
template<>
struct MD5Sum< ::wam_control::PlayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::Play >::value();
  }
  static const char* value(const ::wam_control::PlayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::PlayResponse> should match 
// service_traits::DataType< ::wam_control::Play > 
template<>
struct DataType< ::wam_control::PlayResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::Play >::value();
  }
  static const char* value(const ::wam_control::PlayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_PLAY_H
