// Generated by gencpp from file wam_control/PoseMove.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_POSEMOVE_H
#define WAM_CONTROL_MESSAGE_POSEMOVE_H

#include <ros/service_traits.h>


#include <wam_control/PoseMoveRequest.h>
#include <wam_control/PoseMoveResponse.h>


namespace wam_control
{

struct PoseMove
{

typedef PoseMoveRequest Request;
typedef PoseMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PoseMove
} // namespace wam_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wam_control::PoseMove > {
  static const char* value()
  {
    return "f192399f711a48924df9a394d37edd67";
  }

  static const char* value(const ::wam_control::PoseMove&) { return value(); }
};

template<>
struct DataType< ::wam_control::PoseMove > {
  static const char* value()
  {
    return "wam_control/PoseMove";
  }

  static const char* value(const ::wam_control::PoseMove&) { return value(); }
};


// service_traits::MD5Sum< ::wam_control::PoseMoveRequest> should match 
// service_traits::MD5Sum< ::wam_control::PoseMove > 
template<>
struct MD5Sum< ::wam_control::PoseMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::PoseMove >::value();
  }
  static const char* value(const ::wam_control::PoseMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::PoseMoveRequest> should match 
// service_traits::DataType< ::wam_control::PoseMove > 
template<>
struct DataType< ::wam_control::PoseMoveRequest>
{
  static const char* value()
  {
    return DataType< ::wam_control::PoseMove >::value();
  }
  static const char* value(const ::wam_control::PoseMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wam_control::PoseMoveResponse> should match 
// service_traits::MD5Sum< ::wam_control::PoseMove > 
template<>
struct MD5Sum< ::wam_control::PoseMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wam_control::PoseMove >::value();
  }
  static const char* value(const ::wam_control::PoseMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wam_control::PoseMoveResponse> should match 
// service_traits::DataType< ::wam_control::PoseMove > 
template<>
struct DataType< ::wam_control::PoseMoveResponse>
{
  static const char* value()
  {
    return DataType< ::wam_control::PoseMove >::value();
  }
  static const char* value(const ::wam_control::PoseMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_POSEMOVE_H
