// Generated by gencpp from file wam_control/RTCartVel.msg
// DO NOT EDIT!


#ifndef WAM_CONTROL_MESSAGE_RTCARTVEL_H
#define WAM_CONTROL_MESSAGE_RTCARTVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wam_control
{
template <class ContainerAllocator>
struct RTCartVel_
{
  typedef RTCartVel_<ContainerAllocator> Type;

  RTCartVel_()
    : direction()
    , magnitude(0.0)  {
      direction.assign(0.0);
  }
  RTCartVel_(const ContainerAllocator& _alloc)
    : direction()
    , magnitude(0.0)  {
  (void)_alloc;
      direction.assign(0.0);
  }



   typedef boost::array<float, 3>  _direction_type;
  _direction_type direction;

   typedef float _magnitude_type;
  _magnitude_type magnitude;




  typedef boost::shared_ptr< ::wam_control::RTCartVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wam_control::RTCartVel_<ContainerAllocator> const> ConstPtr;

}; // struct RTCartVel_

typedef ::wam_control::RTCartVel_<std::allocator<void> > RTCartVel;

typedef boost::shared_ptr< ::wam_control::RTCartVel > RTCartVelPtr;
typedef boost::shared_ptr< ::wam_control::RTCartVel const> RTCartVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wam_control::RTCartVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wam_control::RTCartVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wam_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'wam_control': ['/home/fuego/reach_and_grasp_ws/src/wam_control/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wam_control::RTCartVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wam_control::RTCartVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_control::RTCartVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wam_control::RTCartVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_control::RTCartVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wam_control::RTCartVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wam_control::RTCartVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bde6e49ce1902bc915138d25af0e9ef1";
  }

  static const char* value(const ::wam_control::RTCartVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbde6e49ce1902bc9ULL;
  static const uint64_t static_value2 = 0x15138d25af0e9ef1ULL;
};

template<class ContainerAllocator>
struct DataType< ::wam_control::RTCartVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wam_control/RTCartVel";
  }

  static const char* value(const ::wam_control::RTCartVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wam_control::RTCartVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] direction\n\
float32    magnitude\n\
";
  }

  static const char* value(const ::wam_control::RTCartVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wam_control::RTCartVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.magnitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RTCartVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wam_control::RTCartVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wam_control::RTCartVel_<ContainerAllocator>& v)
  {
    s << indent << "direction[]" << std::endl;
    for (size_t i = 0; i < v.direction.size(); ++i)
    {
      s << indent << "  direction[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.direction[i]);
    }
    s << indent << "magnitude: ";
    Printer<float>::stream(s, indent + "  ", v.magnitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAM_CONTROL_MESSAGE_RTCARTVEL_H
