// Generated by gencpp from file hil_servoing/TaskIds.msg
// DO NOT EDIT!


#ifndef HIL_SERVOING_MESSAGE_TASKIDS_H
#define HIL_SERVOING_MESSAGE_TASKIDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hil_servoing
{
template <class ContainerAllocator>
struct TaskIds_
{
  typedef TaskIds_<ContainerAllocator> Type;

  TaskIds_()
    : ids()  {
    }
  TaskIds_(const ContainerAllocator& _alloc)
    : ids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _ids_type;
  _ids_type ids;




  typedef boost::shared_ptr< ::hil_servoing::TaskIds_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hil_servoing::TaskIds_<ContainerAllocator> const> ConstPtr;

}; // struct TaskIds_

typedef ::hil_servoing::TaskIds_<std::allocator<void> > TaskIds;

typedef boost::shared_ptr< ::hil_servoing::TaskIds > TaskIdsPtr;
typedef boost::shared_ptr< ::hil_servoing::TaskIds const> TaskIdsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hil_servoing::TaskIds_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hil_servoing::TaskIds_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hil_servoing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hil_servoing': ['/home/froglake/reach_and_grasp_ws/src/hil_servoing/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hil_servoing::TaskIds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hil_servoing::TaskIds_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hil_servoing::TaskIds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hil_servoing::TaskIds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hil_servoing::TaskIds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hil_servoing::TaskIds_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hil_servoing::TaskIds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc9d44a4676b25d54541ab8ee46f8ed3";
  }

  static const char* value(const ::hil_servoing::TaskIds_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc9d44a4676b25d5ULL;
  static const uint64_t static_value2 = 0x4541ab8ee46f8ed3ULL;
};

template<class ContainerAllocator>
struct DataType< ::hil_servoing::TaskIds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hil_servoing/TaskIds";
  }

  static const char* value(const ::hil_servoing::TaskIds_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hil_servoing::TaskIds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] ids\n\
";
  }

  static const char* value(const ::hil_servoing::TaskIds_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hil_servoing::TaskIds_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskIds_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hil_servoing::TaskIds_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hil_servoing::TaskIds_<ContainerAllocator>& v)
  {
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIL_SERVOING_MESSAGE_TASKIDS_H
