// Generated by gencpp from file hil_servoing/TrackPoint.msg
// DO NOT EDIT!


#ifndef HIL_SERVOING_MESSAGE_TRACKPOINT_H
#define HIL_SERVOING_MESSAGE_TRACKPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hil_servoing
{
template <class ContainerAllocator>
struct TrackPoint_
{
  typedef TrackPoint_<ContainerAllocator> Type;

  TrackPoint_()
    : x(0.0)
    , y(0.0)  {
    }
  TrackPoint_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::hil_servoing::TrackPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hil_servoing::TrackPoint_<ContainerAllocator> const> ConstPtr;

}; // struct TrackPoint_

typedef ::hil_servoing::TrackPoint_<std::allocator<void> > TrackPoint;

typedef boost::shared_ptr< ::hil_servoing::TrackPoint > TrackPointPtr;
typedef boost::shared_ptr< ::hil_servoing::TrackPoint const> TrackPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hil_servoing::TrackPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hil_servoing::TrackPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hil_servoing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hil_servoing': ['/home/fuego/reach_and_grasp_ws/src/hil_servoing/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hil_servoing::TrackPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hil_servoing::TrackPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hil_servoing::TrackPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hil_servoing::TrackPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hil_servoing::TrackPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hil_servoing::TrackPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hil_servoing::TrackPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const ::hil_servoing::TrackPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::hil_servoing::TrackPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hil_servoing/TrackPoint";
  }

  static const char* value(const ::hil_servoing::TrackPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hil_servoing::TrackPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::hil_servoing::TrackPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hil_servoing::TrackPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hil_servoing::TrackPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hil_servoing::TrackPoint_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIL_SERVOING_MESSAGE_TRACKPOINT_H
